[workload]
wtype = stress-workload
name = stress_workload_ivfflat_sample
limit = 10

[dataset]
base = dataset/SPACEV/base.npy
search = dataset/SPACEV/query.npy
gt_trace = output/workloads/stress_ivfflat_trace.pkl
split_num = 100000
dim = 128

[postgres]
host = 127.0.0.1
port = 5432
user = postgres
password = postgres
database = postgres

datastore = spacev_ivfflat_10m
datastore_clean =
psql_config = configs/postgresql.conf
pg_log = output/postgres.log

[pgvector]
type = ivfflat
index_name = items_ivfflat_idx
distance = vector_l2_ops
nlist = 1000
nprobe = 16

[env]
# AKER_CONFIG_PATH = configs/aker_bootstrap.ini
